"""baseline_schema

Revision ID: cd98fe1ad11d
Revises: 
Create Date: 2026-04-14 08:26:56.730165+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd98fe1ad11d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limits',
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_key', sa.String(length=255), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.BigInteger(), nullable=True),
    sa.Column('last_attempt_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('scope_type', 'scope_key')
    )
    op.create_index('idx_auth_rate_limits_blocked_until', 'auth_rate_limits', ['blocked_until'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('menu_type', sa.String(length=32), nullable=False),
    sa.Column('route_path', sa.String(length=512), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=True),
    sa.Column('redirect_path', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('component_key', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('open_mode', sa.String(length=16), nullable=False),
    sa.Column('is_cacheable', sa.Boolean(), nullable=False),
    sa.Column('is_affix', sa.Boolean(), nullable=False),
    sa.Column('active_menu_path', sa.String(length=512), nullable=True),
    sa.Column('badge_text', sa.String(length=64), nullable=True),
    sa.Column('badge_type', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_menus_parent_id', 'menus', ['parent_id'], unique=False)
    op.create_index('idx_menus_sort_order', 'menus', ['sort_order'], unique=False)
    op.create_index('idx_menus_visible_enabled', 'menus', ['is_visible', 'is_enabled'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('task_queue',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_queue_created_at', 'task_queue', ['created_at'], unique=False)
    op.create_index('idx_task_queue_status', 'task_queue', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('remember', sa.Boolean(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.BigInteger(), nullable=False),
    sa.Column('revoked_at', sa.BigInteger(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_sessions_revoked_at', 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index('idx_auth_sessions_user_id', 'auth_sessions', ['user_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_assets_asset_type', 'media_assets', ['asset_type'], unique=False)
    op.create_index('idx_media_assets_owner_user_id', 'media_assets', ['owner_user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('token_jti', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('revoked_at', sa.BigInteger(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti')
    )
    op.create_index('idx_refresh_tokens_session_id', 'refresh_tokens', ['session_id'], unique=False)
    op.create_index('idx_refresh_tokens_token_jti', 'refresh_tokens', ['token_jti'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_menus',
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_index('idx_role_menus_menu_id', 'role_menus', ['menu_id'], unique=False)
    op.create_index('idx_role_menus_role_id', 'role_menus', ['role_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_platform', sa.String(length=64), nullable=False),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('generated_media_url', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_asset_id', sa.String(length=32), nullable=True),
    sa.Column('script_overview_json', sa.Text(), nullable=True),
    sa.Column('ecommerce_analysis_json', sa.Text(), nullable=True),
    sa.Column('source_analysis_json', sa.Text(), nullable=True),
    sa.Column('timeline_segments_json', sa.Text(), nullable=True),
    sa.Column('video_generation_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_updated_at', 'projects', ['updated_at'], unique=False)
    op.create_index('idx_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('trigger_message_id', sa.String(length=32), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('input_asset_id', sa.String(length=32), nullable=True),
    sa.Column('output_asset_id', sa.String(length=32), nullable=True),
    sa.Column('parent_job_id', sa.String(length=32), nullable=True),
    sa.Column('source_job_id', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['input_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('idx_jobs_project_id', 'jobs', ['project_id'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('project_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('message_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['project_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_messages_created_at', 'project_messages', ['created_at'], unique=False)
    op.create_index('idx_project_messages_project_id', 'project_messages', ['project_id'], unique=False)
    op.create_table('project_task_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_task_steps_project_id', 'project_task_steps', ['project_id'], unique=False)
    op.create_index('idx_project_task_steps_status', 'project_task_steps', ['status'], unique=False)
    op.create_table('motion_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_video_asset_id', sa.String(length=32), nullable=True),
    sa.Column('clip_asset_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=True),
    sa.Column('action_label', sa.String(length=128), nullable=True),
    sa.Column('entrance_style', sa.String(length=128), nullable=True),
    sa.Column('emotion_label', sa.String(length=128), nullable=True),
    sa.Column('temperament_label', sa.String(length=128), nullable=True),
    sa.Column('scene_label', sa.String(length=128), nullable=True),
    sa.Column('camera_motion', sa.String(length=64), nullable=True),
    sa.Column('camera_shot', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('asset_candidate', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('copyright_risk_level', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['clip_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_video_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_motion_assets_action_label', 'motion_assets', ['action_label'], unique=False)
    op.create_index('idx_motion_assets_owner_user_id', 'motion_assets', ['owner_user_id'], unique=False)
    op.create_index('idx_motion_assets_project_id', 'motion_assets', ['project_id'], unique=False)
    op.create_index('idx_motion_assets_review_status', 'motion_assets', ['review_status'], unique=False)
    op.create_index('idx_motion_assets_scene_label', 'motion_assets', ['scene_label'], unique=False)
    op.create_index('idx_motion_assets_source_video_asset_id', 'motion_assets', ['source_video_asset_id'], unique=False)
    op.create_table('shot_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_video_asset_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=True),
    sa.Column('end_frame', sa.Integer(), nullable=True),
    sa.Column('boundary_in_type', sa.String(length=32), nullable=True),
    sa.Column('boundary_out_type', sa.String(length=32), nullable=True),
    sa.Column('detector_name', sa.String(length=64), nullable=True),
    sa.Column('detector_version', sa.String(length=32), nullable=True),
    sa.Column('detector_config_json', sa.Text(), nullable=True),
    sa.Column('keyframe_asset_ids_json', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('visual_summary', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('shot_type_code', sa.String(length=64), nullable=True),
    sa.Column('camera_angle_code', sa.String(length=64), nullable=True),
    sa.Column('camera_motion_code', sa.String(length=64), nullable=True),
    sa.Column('scene_label', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lighting_code', sa.String(length=64), nullable=True),
    sa.Column('dominant_color', sa.String(length=32), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('face_regions_json', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'segment_index', name='uq_shot_segments_project_segment')
    )
    op.create_index('idx_shot_segments_job_id', 'shot_segments', ['job_id'], unique=False)
    op.create_index('idx_shot_segments_project_id', 'shot_segments', ['project_id'], unique=False)
    op.create_index('idx_shot_segments_source_video_asset_id', 'shot_segments', ['source_video_asset_id'], unique=False)
    op.create_index('idx_shot_segments_start_ms', 'shot_segments', ['project_id', 'start_ms'], unique=False)
    op.create_table('storyboards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('source_video_asset_id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generator_provider', sa.String(length=64), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_no', name='uq_storyboards_project_version')
    )
    op.create_index('idx_storyboards_project_id', 'storyboards', ['project_id'], unique=False)
    op.create_index('idx_storyboards_source_video_asset_id', 'storyboards', ['source_video_asset_id'], unique=False)
    op.create_table('storyboard_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storyboard_id', sa.String(length=32), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('shot_type_code', sa.String(length=64), nullable=True),
    sa.Column('camera_angle_code', sa.String(length=64), nullable=True),
    sa.Column('camera_motion_code', sa.String(length=64), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=False),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('ocr_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyboard_id', 'item_index', name='uq_storyboard_items_storyboard_index')
    )
    op.create_index('idx_storyboard_items_start_ms', 'storyboard_items', ['storyboard_id', 'start_ms'], unique=False)
    op.create_index('idx_storyboard_items_storyboard_id', 'storyboard_items', ['storyboard_id'], unique=False)
    op.create_table('storyboard_item_segments',
    sa.Column('storyboard_item_id', sa.String(length=32), nullable=False),
    sa.Column('shot_segment_id', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shot_segment_id'], ['shot_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storyboard_item_id'], ['storyboard_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('storyboard_item_id', 'shot_segment_id')
    )
    op.create_index('idx_storyboard_item_segments_shot_segment_id', 'storyboard_item_segments', ['shot_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_storyboard_item_segments_shot_segment_id', table_name='storyboard_item_segments')
    op.drop_table('storyboard_item_segments')
    op.drop_index('idx_storyboard_items_storyboard_id', table_name='storyboard_items')
    op.drop_index('idx_storyboard_items_start_ms', table_name='storyboard_items')
    op.drop_table('storyboard_items')
    op.drop_index('idx_storyboards_source_video_asset_id', table_name='storyboards')
    op.drop_index('idx_storyboards_project_id', table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index('idx_shot_segments_start_ms', table_name='shot_segments')
    op.drop_index('idx_shot_segments_source_video_asset_id', table_name='shot_segments')
    op.drop_index('idx_shot_segments_project_id', table_name='shot_segments')
    op.drop_index('idx_shot_segments_job_id', table_name='shot_segments')
    op.drop_table('shot_segments')
    op.drop_index('idx_motion_assets_source_video_asset_id', table_name='motion_assets')
    op.drop_index('idx_motion_assets_scene_label', table_name='motion_assets')
    op.drop_index('idx_motion_assets_review_status', table_name='motion_assets')
    op.drop_index('idx_motion_assets_project_id', table_name='motion_assets')
    op.drop_index('idx_motion_assets_owner_user_id', table_name='motion_assets')
    op.drop_index('idx_motion_assets_action_label', table_name='motion_assets')
    op.drop_table('motion_assets')
    op.drop_index('idx_project_task_steps_status', table_name='project_task_steps')
    op.drop_index('idx_project_task_steps_project_id', table_name='project_task_steps')
    op.drop_table('project_task_steps')
    op.drop_index('idx_project_messages_project_id', table_name='project_messages')
    op.drop_index('idx_project_messages_created_at', table_name='project_messages')
    op.drop_table('project_messages')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_project_id', table_name='jobs')
    op.drop_index('idx_jobs_job_type', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_projects_user_id', table_name='projects')
    op.drop_index('idx_projects_updated_at', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_user_roles_user_id', table_name='user_roles')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('system_settings')
    op.drop_index('idx_role_menus_role_id', table_name='role_menus')
    op.drop_index('idx_role_menus_menu_id', table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_jti', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_session_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_media_assets_owner_user_id', table_name='media_assets')
    op.drop_index('idx_media_assets_asset_type', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('idx_auth_sessions_user_id', table_name='auth_sessions')
    op.drop_index('idx_auth_sessions_revoked_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_index('idx_task_queue_status', table_name='task_queue')
    op.drop_index('idx_task_queue_created_at', table_name='task_queue')
    op.drop_table('task_queue')
    op.drop_table('roles')
    op.drop_index('idx_menus_visible_enabled', table_name='menus')
    op.drop_index('idx_menus_sort_order', table_name='menus')
    op.drop_index('idx_menus_parent_id', table_name='menus')
    op.drop_table('menus')
    op.drop_index('idx_auth_rate_limits_blocked_until', table_name='auth_rate_limits')
    op.drop_table('auth_rate_limits')
    # ### end Alembic commands ###
