DEFAULT_PERMISSION_DEFINITIONS = (
    {
        "code": "profile.read",
        "name": "查看个人资料",
        "group_name": "auth",
        "description": "查看当前登录用户的基础资料。",
    },
    {
        "code": "profile.password.change",
        "name": "修改个人密码",
        "group_name": "auth",
        "description": "修改当前登录用户自己的密码。",
    },
    {
        "code": "users.view",
        "name": "查看用户",
        "group_name": "users",
        "description": "查看系统中的用户列表与详情。",
    },
    {
        "code": "users.create",
        "name": "创建用户",
        "group_name": "users",
        "description": "创建新的后台用户。",
    },
    {
        "code": "users.update",
        "name": "更新用户",
        "group_name": "users",
        "description": "修改用户状态、昵称、邮箱等信息。",
    },
    {
        "code": "users.delete",
        "name": "删除用户",
        "group_name": "users",
        "description": "删除后台用户及其关联角色与会话信息。",
    },
    {
        "code": "users.assign_roles",
        "name": "分配用户角色",
        "group_name": "users",
        "description": "为用户分配或调整角色。",
    },
    {
        "code": "roles.view",
        "name": "查看角色",
        "group_name": "roles",
        "description": "查看角色与角色权限。",
    },
    {
        "code": "roles.create",
        "name": "创建角色",
        "group_name": "roles",
        "description": "创建新的角色。",
    },
    {
        "code": "roles.update",
        "name": "更新角色",
        "group_name": "roles",
        "description": "修改角色名称、描述等信息。",
    },
    {
        "code": "roles.delete",
        "name": "删除角色",
        "group_name": "roles",
        "description": "删除自定义角色。",
    },
    {
        "code": "roles.assign_permissions",
        "name": "分配角色权限",
        "group_name": "roles",
        "description": "为角色绑定权限集合。",
    },
    {
        "code": "permissions.view",
        "name": "查看权限",
        "group_name": "permissions",
        "description": "查看系统中的权限定义。",
    },
    {
        "code": "permissions.create",
        "name": "创建权限",
        "group_name": "permissions",
        "description": "创建自定义权限。",
    },
    {
        "code": "files.upload",
        "name": "上传文件",
        "group_name": "files",
        "description": "上传业务文件。",
    },
    {
        "code": "assets.upload",
        "name": "上传资产",
        "group_name": "assets",
        "description": "上传视频等媒体资产。",
    },
    {
        "code": "motion_assets.read",
        "name": "查看动作资产",
        "group_name": "motion_assets",
        "description": "查看动作资产候选、标签与检索结果。",
    },
    {
        "code": "conversations.read",
        "name": "查看会话",
        "group_name": "conversations",
        "description": "查看会话列表与会话消息。",
    },
    {
        "code": "conversations.write",
        "name": "管理会话",
        "group_name": "conversations",
        "description": "创建会话并发送会话消息。",
    },
    {
        "code": "jobs.read",
        "name": "查看任务",
        "group_name": "jobs",
        "description": "查看分析、复刻等任务状态。",
    },
    {
        "code": "settings.view",
        "name": "查看系统设置",
        "group_name": "settings",
        "description": "查看系统代理、AI 模型和视频复刻配置。",
    },
    {
        "code": "settings.update",
        "name": "更新系统设置",
        "group_name": "settings",
        "description": "修改系统代理、AI 模型和视频复刻配置。",
    },
    {
        "code": "tiktok.fetch",
        "name": "获取 TikTok 信息",
        "group_name": "tiktok",
        "description": "查询 TikTok 视频详情。",
    },
)

DEFAULT_ROLE_DEFINITIONS = (
    {
        "code": "super_admin",
        "name": "超级管理员",
        "description": "拥有系统内所有权限。",
        "is_system": 1,
        "permission_codes": "*",
    },
    {
        "code": "admin",
        "name": "管理员",
        "description": "负责日常用户和角色维护。",
        "is_system": 1,
        "permission_codes": (
            "profile.read",
            "profile.password.change",
            "users.view",
            "users.create",
            "users.update",
            "users.delete",
            "users.assign_roles",
            "roles.view",
            "roles.create",
            "roles.update",
            "roles.delete",
            "roles.assign_permissions",
            "permissions.view",
            "files.upload",
            "assets.upload",
            "motion_assets.read",
            "conversations.read",
            "conversations.write",
            "jobs.read",
            "settings.view",
            "settings.update",
            "tiktok.fetch",
        ),
    },
    {
        "code": "user",
        "name": "普通用户",
        "description": "系统默认用户角色。",
        "is_system": 1,
        "permission_codes": (
            "profile.read",
            "profile.password.change",
            "motion_assets.read",
            "conversations.read",
            "jobs.read",
        ),
    },
)
