DEFAULT_PERMISSION_DEFINITIONS = ()

REMOVED_DEFAULT_MENU_CODES = (
    "system.permissions",
)

DEFAULT_ROLE_DEFINITIONS = (
    {
        "code": "super_admin",
        "name": "超级管理员",
        "description": "拥有系统内所有权限。",
        "is_system": 1,
    },
    {
        "code": "admin",
        "name": "管理员",
        "description": "负责日常用户和角色维护。",
        "is_system": 1,
    },
    {
        "code": "user",
        "name": "普通用户",
        "description": "系统默认用户角色。",
        "is_system": 1,
    },
)

DEFAULT_MENU_DEFINITIONS = (
    {
        "code": "dashboard.root",
        "parent_code": None,
        "title": "仪表盘",
        "menu_type": "menu",
        "route_path": "/dashboard",
        "route_name": "dashboard",
        "redirect_path": None,
        "icon": "LayoutDashboard",
        "component_key": "dashboard",
        "sort_order": 10,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": "系统首页",
        "meta_json": {"section": "main"},
    },
    {
        "code": "system.root",
        "parent_code": None,
        "title": "系统",
        "menu_type": "directory",
        "route_path": "",
        "route_name": "system",
        "redirect_path": None,
        "icon": "Settings",
        "component_key": None,
        "sort_order": 20,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": "系统管理目录",
        "meta_json": {"section": "system"},
    },
    {
        "code": "system.users",
        "parent_code": "system.root",
        "title": "用户管理",
        "menu_type": "menu",
        "route_path": "/users",
        "route_name": "users",
        "redirect_path": None,
        "icon": "UserCog",
        "component_key": "users",
        "sort_order": 10,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": None,
        "meta_json": {"section": "system"},
    },
    {
        "code": "system.roles",
        "parent_code": "system.root",
        "title": "角色管理",
        "menu_type": "menu",
        "route_path": "/roles",
        "route_name": "roles",
        "redirect_path": None,
        "icon": "ShieldCheck",
        "component_key": "roles",
        "sort_order": 20,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": None,
        "meta_json": {"section": "system"},
    },
    {
        "code": "system.menus",
        "parent_code": "system.root",
        "title": "菜单管理",
        "menu_type": "menu",
        "route_path": "/menus",
        "route_name": "menus",
        "redirect_path": None,
        "icon": "FolderTree",
        "component_key": "menus",
        "sort_order": 30,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": None,
        "meta_json": {"section": "system"},
    },
    {
        "code": "creation.root",
        "parent_code": None,
        "title": "创作",
        "menu_type": "directory",
        "route_path": "",
        "route_name": "creation",
        "redirect_path": None,
        "icon": "Sparkles",
        "component_key": None,
        "sort_order": 30,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": "创作工作区目录",
        "meta_json": {"section": "creation"},
    },
    {
        "code": "video.analysis",
        "parent_code": "creation.root",
        "title": "视频分析",
        "menu_type": "menu",
        "route_path": "/video/workbench",
        "route_name": "video-workbench",
        "redirect_path": None,
        "icon": "Captions",
        "component_key": "video-workbench",
        "sort_order": 10,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": None,
        "meta_json": {"section": "creation"},
    },
    {
        "code": "space.root",
        "parent_code": None,
        "title": "空间",
        "menu_type": "directory",
        "route_path": "",
        "route_name": "space",
        "redirect_path": None,
        "icon": "HardDrive",
        "component_key": None,
        "sort_order": 40,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": "素材空间目录",
        "meta_json": {"section": "space"},
    },
    {
        "code": "space.assets",
        "parent_code": "space.root",
        "title": "动态资产",
        "menu_type": "menu",
        "route_path": "/assets",
        "route_name": "assets",
        "redirect_path": None,
        "icon": "Shapes",
        "component_key": "assets",
        "sort_order": 10,
        "is_visible": 1,
        "is_enabled": 1,
        "is_external": 0,
        "open_mode": "self",
        "is_cacheable": 0,
        "is_affix": 0,
        "active_menu_path": None,
        "badge_text": None,
        "badge_type": None,
        "remark": None,
        "meta_json": {"section": "space"},
    },
)

DEFAULT_ROLE_MENU_CODES = {
    "super_admin": "*",
    "admin": (
        "dashboard.root",
        "system.root",
        "system.users",
        "system.roles",
        "system.menus",
        "creation.root",
        "video.analysis",
        "space.root",
        "space.assets",
    ),
    "user": (
        "dashboard.root",
        "creation.root",
        "video.analysis",
        "space.root",
        "space.assets",
    ),
}
